#!/usr/local/bin/php
<?php
/******************************************************************************************
 *
 *  Usage: run [name1 [name2 [...]]] - runs test from files name1.php, name2.php, ...
 *                                         or all tests if no args
 *
 *****************************************************************************************/
define('TEST_MODE', true);

require_once(__DIR__.'/../vendor/tipy/TipyTestSuite.php');

array_shift($argv);
$runner = new TestRunner($argv);
$runner->fixtures  = array(__DIR__.'/fixtures/tipy/unit_fixtures');   // path to fixtures/xxx.sql or array of such pathes
$runner->dirs      = array(__DIR__.'/unit/tipy');                     // path to test files folder or array of such pathes
$runner->useDumper = false;                                           // If TRUE, use DB clone structure from production
$runner->run();

